# 로컬 개발 환경에서 사용하는 도커 파일입니다.
# 도커 환경에서 Hot Reload를 지원하기 위해 사용합니다.
# 프로덕션 용 도커 파일은 `Dockerfile.Build`를 참고해주세요.
FROM node:20-alpine

WORKDIR /sight

COPY package*.json ./
RUN npm ci

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
