name: Test coverage for pull request

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      # - name: Prepare yarn
      #   run: corepack enable && corepack prepare yarn@4.6.0 --activate

      - name: Install dependencies
        # run: yarn install --immutable
        run: npm ci

      - name: Run tests
        # run: yarn test:cov --maxWorkers=100%
        run: npm run test:cov -- --maxWorkers=100%

      - name: Coverage
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage/lcov.info'
